services:

  caddy:
    image: caddy:2
    environment:
      - LILA_DOMAIN=preview.${SUBDOMAIN:-test}.lichess.app
      - LILA_URL=https://preview.${SUBDOMAIN:-test}.lichess.app
    volumes:
      - ./conf/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - frontend
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.services.lila-preview-${SUBDOMAIN:-test}.loadbalancer.server.port=80
      - traefik.http.routers.lila-preview-${SUBDOMAIN:-test}.rule=Host(`preview.${SUBDOMAIN:-test}.lichess.app`)
      - traefik.http.routers.lila-preview-${SUBDOMAIN:-test}.entrypoints=websecure
      - traefik.http.routers.lila-preview-${SUBDOMAIN:-test}.tls=true
      - traefik.http.routers.lila-preview-${SUBDOMAIN:-test}.tls.certresolver=myresolver
      - traefik.http.routers.lila-preview-protected-${SUBDOMAIN:-test}.rule=Host(`preview.${SUBDOMAIN:-test}.lichess.app`) && (PathPrefix(`/player`) || PathPrefix(`/forum`) || PathPrefix(`/team`) || PathPrefix(`/blog`) || PathPrefix(`/games`) || PathPrefix(`/class`) || PathPrefix(`/tournament/leaderboard`) || PathPrefix(`/training`) || PathPrefix(`/streak`) || PathPrefix(`/storm`) || PathPrefix(`/racer`) || PathPrefix(`/insights`) || PathPrefix(`/opening`) || PathPrefix(`/analysis/pgn`))
      - traefik.http.routers.lila-preview-protected-${SUBDOMAIN:-test}.entrypoints=websecure
      - traefik.http.routers.lila-preview-protected-${SUBDOMAIN:-test}.tls=true
      - traefik.http.routers.lila-preview-protected-${SUBDOMAIN:-test}.tls.certresolver=myresolver
      - traefik.http.routers.lila-preview-protected-${SUBDOMAIN:-test}.middlewares=authentik@file
      - traefik.http.routers.lila-preview-protected-${SUBDOMAIN:-test}.priority=100
      - traefik.http.routers.lila-preview-protected-${SUBDOMAIN:-test}.service=lila-preview-${SUBDOMAIN:-test}
      - traefik.http.routers.lila-preview-outpost-${SUBDOMAIN:-test}.rule=Host(`preview.${SUBDOMAIN:-test}.lichess.app`) && PathPrefix(`/outpost.goauthentik.io`)
      - traefik.http.routers.lila-preview-outpost-${SUBDOMAIN:-test}.entrypoints=websecure
      - traefik.http.routers.lila-preview-outpost-${SUBDOMAIN:-test}.tls=true
      - traefik.http.routers.lila-preview-outpost-${SUBDOMAIN:-test}.tls.certresolver=myresolver
      - traefik.http.routers.lila-preview-outpost-${SUBDOMAIN:-test}.priority=200
      - traefik.http.routers.lila-preview-outpost-${SUBDOMAIN:-test}.service=authentik-server@file

  lila:
    image: ghcr.io/lichess-org/lila-server:${LILA_SERVER_TAG:-latest}
    environment:
      - LILA_DOMAIN=preview.${SUBDOMAIN:-test}.lichess.app
      - LILA_URL=https://preview.${SUBDOMAIN:-test}.lichess.app
      - LILA_SITE_NAME=${LILA_SITE_NAME:-lichess preview}
      - LILA_EXPLORER_ENDPOINT=https://preview.${SUBDOMAIN:-test}.explorer.lichess.app
    volumes:
      - ./conf/lila.conf:/lila/conf/application.conf
      - lila-assets-data:/lila/public:ro
    secrets:
      - lila_preview_firebase_service_account

  lila_assets:
    image: ghcr.io/lichess-org/lila-assets:${LILA_ASSETS_TAG:-latest}
    volumes:
      - lila-assets-data:/assets:rw
      - ./scripts/update-asset-volume.sh:/docker-entrypoint.d/50-update-assets.sh:ro

  lila_ws:
    image: ghcr.io/lichess-org/lila-ws:${LILA_WS_TAG:-latest}
    environment:
      - CONFIG_FORCE_csrf.origin=https://preview.${SUBDOMAIN:-test}.lichess.app
      - CONFIG_FORCE_mongo_uri=mongodb://mongodb:27017/lichess?appName=lila-ws
      - CONFIG_FORCE_redis.uri=redis://redis

  mongodb:
    image: mongo:8.2-noble

  redis:
    image: redis:8

  openingexplorer:
    image: ghcr.io/lichess-org/lila-openingexplorer:latest
    environment:
      - LILA_URL=https://preview.${SUBDOMAIN:-test}.lichess.app
      - EXPLORER_BEARER=lip_openingexplorer-${USER_SEED_PASSWORD:-password}
    volumes:
      - openingexplorer-data:/app/_db
    networks:
      - frontend
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.services.lila-explorer-${SUBDOMAIN:-test}.loadbalancer.server.port=9002
      - traefik.http.routers.lila-explorer-${SUBDOMAIN:-test}.rule=Host(`preview.${SUBDOMAIN:-test}.explorer.lichess.app`)
      - traefik.http.routers.lila-explorer-${SUBDOMAIN:-test}.entrypoints=websecure
      - traefik.http.routers.lila-explorer-${SUBDOMAIN:-test}.tls=true
      - traefik.http.routers.lila-explorer-${SUBDOMAIN:-test}.tls.certresolver=myresolver
      - traefik.http.routers.lila-explorer-${SUBDOMAIN:-test}.middlewares=explorer-cors-${SUBDOMAIN:-test}
      - traefik.http.middlewares.explorer-cors-${SUBDOMAIN:-test}.headers.accessControlAllowOriginList=https://preview.${SUBDOMAIN:-test}.lichess.app
      - traefik.http.middlewares.explorer-cors-${SUBDOMAIN:-test}.headers.accessControlAllowCredentials=true
      - traefik.http.routers.lila-explorer-blocked-${SUBDOMAIN:-test}.rule=Host(`preview.${SUBDOMAIN:-test}.explorer.lichess.app`) && PathPrefix(`/import`)
      - traefik.http.routers.lila-explorer-blocked-${SUBDOMAIN:-test}.entrypoints=websecure
      - traefik.http.routers.lila-explorer-blocked-${SUBDOMAIN:-test}.tls=true
      - traefik.http.routers.lila-explorer-blocked-${SUBDOMAIN:-test}.tls.certresolver=myresolver
      - traefik.http.routers.lila-explorer-blocked-${SUBDOMAIN:-test}.priority=200
      - traefik.http.routers.lila-explorer-blocked-${SUBDOMAIN:-test}.middlewares=block-import-${SUBDOMAIN:-test}
      - traefik.http.routers.lila-explorer-blocked-${SUBDOMAIN:-test}.service=lila-explorer-${SUBDOMAIN:-test}
      - traefik.http.middlewares.block-import-${SUBDOMAIN:-test}.ipallowlist.sourcerange=192.0.2.1/32

  lila_fishnet:
    image: ghcr.io/lichess-org/lila-fishnet:latest
    environment:
      - REDIS_HOST=redis
      # - HTTP_API_LOGGER=true

  fishnet_play:
    image: niklasf/fishnet:latest
    environment:
      - ENDPOINT=http://lila_fishnet:9665/fishnet
      - MAX_BACKOFF=5
      - STATS_FILE=/stats.json

  fishnet_analysis:
    image: niklasf/fishnet:latest
    environment:
      - ENDPOINT=http://lila:9663/fishnet
      - MAX_BACKOFF=5
      - STATS_FILE=/stats.json

  lila_gif:
    image: ghcr.io/lichess-org/lila-gif:latest
    entrypoint: /usr/local/bin/lila-gif --bind 0.0.0.0:6175

  lila_push:
    image: ghcr.io/lichess-org/lila-push:latest
    entrypoint: /usr/local/bin/lila-push --vapid /app/private.pem --vapid-subject mailto:contact@lichess.org --bind 0.0.0.0:9054
    environment:
      - PUSH_LOG=debug
    volumes:
      - /data/lila-preview/lila-push/private.pem:/app/private.pem:ro

  lila_db_seed:
    image: ghcr.io/lichess-org/lila-db-seed:latest
    environment:
      - USER_SEED_PASSWORD=${USER_SEED_PASSWORD:-password}
    deploy:
      restart_policy:
        condition: none

  picfit:
    image: thoas/picfit:0.16.1
    environment:
      - PICFIT_CONFIG_PATH=/mnt/config.json
    volumes:
      - ./conf/picfit.json:/mnt/config.json

  mailpit:
    image: axllent/mailpit:latest
    environment:
      - MP_WEBROOT=mailpit
      - MP_MAX_AGE=1h
    networks:
      - frontend
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.services.lila-mailpit-${SUBDOMAIN:-test}.loadbalancer.server.port=8025
      - traefik.http.routers.lila-mailpit-${SUBDOMAIN:-test}.rule=Host(`preview.${SUBDOMAIN:-test}.lichess.app`) && PathPrefix(`/mailpit`)
      - traefik.http.routers.lila-mailpit-${SUBDOMAIN:-test}.entrypoints=websecure
      - traefik.http.routers.lila-mailpit-${SUBDOMAIN:-test}.tls=true
      - traefik.http.routers.lila-mailpit-${SUBDOMAIN:-test}.tls.certresolver=myresolver
      - traefik.http.routers.lila-mailpit-${SUBDOMAIN:-test}.priority=100

  mongo_express:
    image: mongo-express:1-20-alpine3.19
    environment:
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_SITE_BASEURL=/mongodb
    depends_on:
      - mongodb
    networks:
      - frontend
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.services.lila-mongo-express-${SUBDOMAIN:-test}.loadbalancer.server.port=8081
      - traefik.http.routers.lila-mongo-express-${SUBDOMAIN:-test}.rule=Host(`preview.${SUBDOMAIN:-test}.lichess.app`) && PathPrefix(`/mongodb`)
      - traefik.http.routers.lila-mongo-express-${SUBDOMAIN:-test}.entrypoints=websecure
      - traefik.http.routers.lila-mongo-express-${SUBDOMAIN:-test}.tls=true
      - traefik.http.routers.lila-mongo-express-${SUBDOMAIN:-test}.tls.certresolver=myresolver
      - traefik.http.routers.lila-mongo-express-${SUBDOMAIN:-test}.middlewares=authentik@file
      - traefik.http.routers.lila-mongo-express-${SUBDOMAIN:-test}.priority=100

volumes:
  lila-assets-data:
  openingexplorer-data:
    external: true

secrets:
  lila_preview_firebase_service_account:
    external: true

networks:
  frontend:
    external: true
  default:
    driver: overlay
    # driver: bridge
