tasks:
  - command: |
      find ./conf -type f -exec sed -i "s/http:\/\/localhost:8080/$(gp url 8080 | sed 's/\//\\\//g')/g" {} \;
      find ./conf -type f -exec sed -i "s/localhost:8080/$(gp url 8080 | cut -c9-)/g" {} \;
      ./lila-docker start
      ./lila-docker gitpod-welcome

ports:
  - port: 8080
    onOpen: open-preview
    name: lichess
    description: Your Lichess development site
  - port: 8025
    onOpen: ignore
    name: mailpit
    description: For debugging emails
  - port: 8081
    onOpen: ignore
    name: mongo-express
    description: "For exploring database schema and contents (u: admin / p: pass)"
  - port: 5601
    onOpen: ignore
    name: kibana
    description: For debugging Elasticsearch

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - scala-lang.scala
