tasks:
  - init: |
      if [ "$GITPOD_HEADLESS" == "true" ]; then
        ./lila-docker fast-setup
      else
        "You can setup prebuilds and get a faster dev environment by following the instructions at https://github.com/lichess-org/lila-docker"
      fi
  - command: |
      ./lila-docker setup

ports:
  - port: 8080
    name: lichess
    description: Lichess dev site
    onOpen: open-preview
  - port: 8025
    name: mailpit
    description: Email inbox
    onOpen: ignore
  - port: 8081
    name: mongo-express
    description: "Database explorer"
    onOpen: ignore
  - port: 8086
    name: influxdb
    description: "Monitoring (u: admin / p: password)"
    onOpen: ignore
  - port: 8089
    name: API docs
    onOpen: ignore
  - port: 8090
    name: chessground
    onOpen: ignore
  - port: 8091
    name: pgn-viewer
    onOpen: ignore
  - port: 9666
    name: lila-engine
    description: External engine
    onOpen: ignore
  - port: 6175
    name: lila-gif
    onOpen: ignore
  - port: 3001
    name: picfit
    onOpen: ignore
  - port: 8092
    name: elasticvue
    description: Elasticsearch manager
    onOpen: ignore
  - port: 9200
    name: elasticsearch
    description: Elasticsearch
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker
    - scala-lang.scala
