tasks:
  - command: |
      find ./conf -type f -exec sed -i "s/http:\/\/localhost:8080/$(gp url 8080 | sed 's/\//\\\//g')/g" {} \;
      find ./conf -type f -exec sed -i "s/localhost:8080/$(gp url 8080 | cut -c9-)/g" {} \;
      ./lila-docker start

ports:
  - port: 8080
    onOpen: open-preview
  - port: 8025
    onOpen: ignore
  - port: 8081
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - scala-lang.scala
