#!/bin/bash -e

if [ ! -z "$GITPOD_WORKSPACE_ID" ]; then
    export IS_GITPOD=true
    export SCHEME=https
    export LILA_DOMAIN=$(gp url 8080 | cut -c9-)
    export PICFIT_DOMAIN=$(gp url 3001 | cut -c9-)
fi

run_setup() {
    rust_cmd setup
    export $(cat .env | xargs)

    docker compose build
    docker compose --profile utils build

    docker compose up -d

    echo "Compiling js/css..."
    docker compose run --rm ui /lila/ui/build

    if [ "$SETUP_DATABASE" = "true" ]; then
        setup_database
    fi

    if [ "$IS_GITPOD" = "true" ]; then
        rust_cmd gitpod-welcome
    fi
}

run_start() {
    if [ -z "$(docker compose ps -a --services | xargs)" ]; then
        run_setup
    else
        if [ ! -z "$(docker compose ps -a --services --status=exited | xargs)" ]; then
            docker compose start
        else
            echo "There are no stopped services to resume"
        fi
    fi
}

run_stop() {
    COMPOSE_PROFILES=$(all_profiles) docker compose stop
}

run_down() {
    COMPOSE_PROFILES=$(all_profiles) docker compose down -v
}

all_profiles() {
    # return all Docker Compose profiles as a comma-separated string
    docker compose config --profiles | xargs | sed -e 's/ /,/g'
}

build_all_profiles() {
    COMPOSE_PROFILES=$(all_profiles) docker compose pull
    COMPOSE_PROFILES=$(all_profiles) docker compose build
}

setup_database() {
    # wait for mongodb to be ready
    while ! docker compose exec mongodb mongo --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
        echo "Waiting for mongodb to be ready..."
        sleep 1
    done

    docker compose run --rm python python /lila-db-seed/spamdb/spamdb.py \
        --uri=mongodb://mongodb/lichess \
        --password=$PASSWORD \
        --su-password=$SU_PASSWORD \
        --streamers \
        --es --es-host=elasticsearch:9200

    docker compose run --rm mongodb mongo --quiet --host mongodb lichess /lila/bin/mongodb/indexes.js
    docker compose run --rm mongodb mongo --quiet --host mongodb lichess /scripts/mongodb/users.js
}

run_formatter() {
    docker compose run --rm -w /lila ui pnpm run format
    docker compose exec chessground pnpm run format || echo "Skipping chessground"
    docker compose exec pgn_viewer pnpm run format || echo "Skipping pgn-viewer"
    docker compose exec lila sbt scalafmtAll || docker compose run --rm --entrypoint "sbt scalafmtAll" lila
}

rust_cmd() {
    if command -v rustup &> /dev/null; then
        # if the host has Rust installed, use it directly
        cargo build --release --manifest-path command/Cargo.toml
        ./command/target/release/command "$@"
    elif [ "$(uname)" = "Darwin" ]; then
        docker run --rm -v "$PWD/command:/command" -w /command messense/cargo-zigbuild:0.18.0 \
            cargo zigbuild --release --target universal2-apple-darwin
        ./command/target/universal2-apple-darwin/release/command "$@"
    else
        docker run --rm -v "$PWD/command:/command" -w /command messense/cargo-zigbuild:0.18.0 \
            cargo zigbuild --release
        ./command/target/release/command "$@"
    fi
}

show_help() {
    echo "Usage: $0 [start|stop|restart|down|build|format]"
}

case $1 in
    --help|-h)
        show_help
        exit 0
        ;;
    start)
        run_start
        ;;
    stop)
        run_stop
        ;;
    restart)
        run_stop && run_start
        ;;
    down)
        run_down
        ;;
    build)
        build_all_profiles
        ;;
    format)
        run_formatter
        ;;
    *)
        show_help
        exit 1
        ;;
esac
