#!/bin/bash -e

cd "$(dirname "$0")"
initial_dir=$(pwd)

# Check if --pull flag is passed
pull_flag=false
if [[ $1 == "--pull" ]]; then
    pull_flag=true
fi

for dir in ./repos/*; do
    # echo "Checking $dir"
    if [[ -d "$dir" ]]; then
        cd "$dir"
        # check if the directory is a git repo
        if [[ ! -d ".git" ]]; then
            echo "Directory $dir is not a git repo."
            cd "$initial_dir"
            continue
        fi
        # check if the git repo is dirty
        if [[ $(git diff --stat) != '' ]]; then
            echo "Repo $dir is dirty."
            cd "$initial_dir"
            continue
        fi
        # check if repo has a main branch or master branch
        main_or_master=""
        if [[ $(git branch --list main) ]]; then
            main_or_master="main"
        elif [[ $(git branch --list master) ]]; then
            main_or_master="master"
        else
            echo "Repo $dir does not have a main or master branch."
            cd "$initial_dir"
            continue
        fi
        # if repo is not on main or master branch, don't do anything
        if [[ $(git branch --show-current) != "$main_or_master" ]]; then
            echo "Repo $dir is not on $main_or_master branch."
            cd "$initial_dir"
            continue
        fi
        # check if repo is up to date
        if [[ $(git rev-list HEAD...upstream/$main_or_master --count) -eq 0 ]]; then
            echo "Repo $dir is up to date."
            cd "$initial_dir"
            continue
        fi

        echo "The repo $dir is behind the remote. Pulling changes."
        if [[ $pull_flag == true ]]; then
            git pull
        fi
        cd "$initial_dir"
        pwd
    fi
done
