[project]
name = "lila-docker"
revision = "1.0"

[profiles.previews]
PORTAINER_API_KEY = { description = "Portainer API key", required = true }
DEPOT_TOKEN = { description = "depot.dev API token", required = true }
