[project]
name = "lila-docker"
revision = "1.0"

[profiles.previews]
PORTAINER_API_KEY = { description = "Portainer API key (only for running deploy.ts locally)", required = false }
DEPOT_TOKEN = { description = "depot.dev API token", required = true }
