include "base"
include "version"

user.password.bpass.secret = "9qEYN0ThHer1KWLNekA76Q=="

net.site.name = "lila"
net.domain = ${?LILA_DOMAIN}
net.socket.domains = [ ${?LILA_DOMAIN} ]
net.asset.base_url = ${?LILA_URL}
net.base_url = ${?LILA_URL}
net.ratelimit = ${?ENABLE_RATE_LIMITING}

mongodb.uri = "mongodb://mongodb?appName=lila"
redis.uri = "redis://redis"

game.gifUrl = "http://lila_gif:6175"

search.enabled = true
search.endpoint = "http://lila_search_app:9673"

memo.picfit.endpointGet = ${?LILA_URL}
memo.picfit.endpointPost = "http://picfit:3001"

mailer.primary.mock = ${?MOCK_EMAIL}
mailer.primary.tls = false
mailer.primary.host = "mailpit"
mailer.primary.port = 1025
mailer.primary.sender = "lichess.org <noreply@lichess.org>"
security.email_confirm.enabled = true

push.firebase.mobile.url = "https://fcm.googleapis.com/v1/projects/lichess-testing-df65f/messages:send"
push.firebase.mobile.json = "/opt/firebase-service-account.json"
push.web.url = "http://lila_push:9054"
push.web.vapid_public_key = "BDTVzVZ3_f83JgH1SJmZrhg-FNZ36Sixc_zrR1-1ZGVHUPmFeU6Q_-JQLN8NF5niYW_1jRU47aPczYA0FbgUCus="

swiss.bbpairing = "/opt/bbpPairings/bbpPairings.exe"

kamon.enabled = ${?ENABLE_MONITORING}
kamon.influxdb.hostname = "influxdb"
kamon.influxdb.authentication.token = "secret"
kamon.metric.tick-interval = 2 seconds
kamon.prometheus.lilaKey = "x"

plan.stripe.keys.public = "pk_test_123"
plan.stripe.keys.secret = "sk_test_123"
plan.payPal.keys.public = "sb"

streamer.twitch.endpoint = "http://caddy/static/twitch-streamers.json"
streamer.twitch.client_id = "twitch-client-id"
streamer.twitch.secret = "twitch-secret"

turnstile.enabled = false

# turnstile.site_key = "1x00000000000000000000AA" # Always passes; Visible; Test successful form submissions
# turnstile.site_key = "2x00000000000000000000AB" # Always fails; Visible; Test error handling and retry logic
# turnstile.site_key = "1x00000000000000000000BB" # Always passes; Invisible; Test invisible widget success flows
# turnstile.site_key = "2x00000000000000000000BB" # Always fails; Invisible; Test invisible widget error handling
turnstile.site_key = "3x00000000000000000000FF" # Forces interactive challenge; Visible; Test user interaction scenarios

turnstile.secret_key = "1x0000000000000000000000000000000AA" # Always passes validation; Test successful token validation
# turnstile.secret_key = "2x0000000000000000000000000000000AA" # Always fails validation; Test validation error handling
# turnstile.secret_key = "3x0000000000000000000000000000000AA" # Returns "token already spent" error; Test duplicate token handling
