include "base"
include "version"

user.password.bpass.secret = "9qEYN0ThHer1KWLNekA76Q=="

net.site.name = ${?LILA_SITE_NAME}
net.domain = ${?LILA_DOMAIN}
net.socket.domains = [ ${?LILA_DOMAIN} ]
net.asset.base_url = ${?LILA_URL}
net.base_url = ${?LILA_URL}
net.email = "contact@example.com"
net.stage.banner = true
net.ratelimit = false

mongodb.uri = "mongodb://mongodb?appName=lila"
redis.uri = "redis://redis"

explorer.internal_endpoint = "http://openingexplorer:9002"
explorer.endpoint = ${?LILA_EXPLORER_ENDPOINT}

game.gifUrl = "http://lila_gif:6175"

search.enabled = false
search.endpoint = "http://lila_search_app:9673"

memo.picfit.endpointGet = ${?LILA_URL}
memo.picfit.endpointPost = "http://picfit:3001"

push.web.url = "http://lila_push:9054"
push.web.vapid_public_key = "BKLo08qJgT9tmfl1dgFpvh5l-Dd17cpuqJ_ZWP-_mcfPjPns89Zjg3W49rrQR_AQJYzn4arFPiSb4_k0HM7NACA"
push.firebase.mobile.url = "https://fcm.googleapis.com/v1/projects/lichess-preview/messages:send"
push.firebase.mobile.jsonPath = "/run/secrets/lila_preview_firebase_service_account"

mailer.primary.mock = false
mailer.primary.tls = false
mailer.primary.host = "mailpit"
mailer.primary.port = 1025
mailer.primary.sender = "lichess.org <noreply@lichess.org>"
security.email_confirm.enabled = true

plan.stripe.keys.public = "pk_test_123"
plan.stripe.keys.secret = "sk_test_123"
plan.payPal.keys.public = "sb"

zulip.domain = ${?ZULIP_DOMAIN}
zulip.user = ${?ZULIP_USER}
zulip.pass = ${?ZULIP_PASS}
